import Sidebar from "@/components/sidebar";

import ReactQueryProvider from "@/providers/ReactQueryProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Safira",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${inter.className} antialiased bg-neutral-900 flex`}>
        <Sidebar />
        <ReactQueryProvider>
          <div className="bg-neutral-100 rounded-xl flex-1 flex flex-col">
            {children}
          </div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
